
INCLUDES = -I/usr/local/include

LIBS = -L/usr/local/lib -pthread -lopencv_highgui -lopencv_core  -lopencv_imgcodecs -lopencv_imgproc -lopencv_objdetect -lopencv_videoio

CFLAGS = -Wall -g -std=c++14


all:
	g++ $(CFLAGS) $(INCLUDES) $(LIBS) traincar.cc -o traincapacity
